// Copyright (c) Foundry Project contributors.
// Licensed under the MIT License.
// See the LICENSE file in the project root for more information.

using Foundry.Telemetry;

namespace Foundry.Core.Models.Configuration;

/// <summary>
/// Represents the configuration consumed by Foundry.Connect during runtime provisioning.
/// </summary>
public sealed record FoundryConnectConfigurationDocument
{
    /// <summary>
    /// Gets the current schema version for Foundry.Connect configuration documents.
    /// </summary>
    public const int CurrentSchemaVersion = ConfigurationSchemaVersions.ConnectCurrent;

    /// <summary>
    /// Gets the schema version of this configuration document.
    /// </summary>
    public int SchemaVersion { get; init; } = CurrentSchemaVersion;

    /// <summary>
    /// Gets media capability flags generated by the app.
    /// </summary>
    public ConnectNetworkCapabilitiesSettings Capabilities { get; init; } = new();

    /// <summary>
    /// Gets network runtime settings generated by the app.
    /// </summary>
    public ConnectNetworkSettings Network { get; init; } = new();

    /// <summary>
    /// Gets wired 802.1X provisioning settings.
    /// </summary>
    public Dot1xSettings Dot1x { get; init; } = new();

    /// <summary>
    /// Gets Wi-Fi provisioning settings.
    /// </summary>
    public WifiSettings Wifi { get; init; } = new();

    /// <summary>
    /// Gets internet connectivity probe settings.
    /// </summary>
    public ConnectInternetProbeSettings InternetProbe { get; init; } = new();

    /// <summary>
    /// Gets the shortcut that opens an interactive PowerShell troubleshooting console.
    /// </summary>
    public TroubleshootingConsoleSettings TroubleshootingConsole { get; init; } = new();

    /// <summary>
    /// Gets telemetry policy and runtime settings consumed by Foundry.Connect.
    /// </summary>
    public TelemetrySettings Telemetry { get; init; } = new();
}
