<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0-windows</TargetFramework>
    <OutputType>Exe</OutputType>
    <IsPackable>false</IsPackable>
    <UseWPF>false</UseWPF>
    <ApplicationIcon></ApplicationIcon>
    <PackageIcon></PackageIcon>
    <RuntimeIdentifiers></RuntimeIdentifiers>
    <GenerateDocumentationFile>false</GenerateDocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="xunit.v3" Version="4.0.1" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Foundry.Core\Foundry.Core.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Content Include="..\Foundry.Core\Assets\7z\x64\7za.exe" Link="Assets\7z\x64\7za.exe" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\Foundry.Core\Assets\7z\arm64\7za.exe" Link="Assets\7z\arm64\7za.exe" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\Foundry.Core\Assets\7z\License.txt" Link="Assets\7z\License.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
    <Content Include="..\Foundry.Core\Assets\7z\readme.txt" Link="Assets\7z\readme.txt" CopyToOutputDirectory="PreserveNewest" CopyToPublishDirectory="PreserveNewest" />
  </ItemGroup>

</Project>
