// Copyright (c) Foundry Project contributors.
// Licensed under the MIT License.
// See the LICENSE file in the project root for more information.

using System.Security.Cryptography;
using Foundry.Core.Services.Configuration;

namespace Foundry.Deploy.Services.System;

/// <summary>
/// Generates deployment-scoped computer-name suffixes.
/// </summary>
public static class ComputerNameSuffixGenerator
{
    private const string AllowedCharacters = "ABCDEFGHIJKLMNOPQRSTUVWXYZ0123456789";

    /// <summary>
    /// Generates an uppercase alphanumeric suffix using a cryptographically secure random source.
    /// </summary>
    /// <returns>A new computer-name suffix.</returns>
    public static string Generate()
    {
        Span<char> suffix = stackalloc char[MachineNamingRules.AutoGeneratedSuffixLength];
        for (int index = 0; index < suffix.Length; index++)
        {
            suffix[index] = AllowedCharacters[RandomNumberGenerator.GetInt32(AllowedCharacters.Length)];
        }

        return new string(suffix);
    }
}
