namespace Foundry.Telemetry;

/// <summary>
/// Represents persisted and generated telemetry settings shared across Foundry runtimes.
/// </summary>
public sealed record TelemetrySettings
{
    /// <summary>
    /// Gets whether telemetry is enabled for the current generated runtime.
    /// </summary>
    public bool IsEnabled { get; init; } = true;

    /// <summary>
    /// Gets the anonymous installation identifier generated by Foundry OSD.
    /// </summary>
    public string InstallId { get; init; } = string.Empty;

    /// <summary>
    /// Gets the PostHog host URL used by the SDK client.
    /// </summary>
    public string HostUrl { get; init; } = TelemetryDefaults.PostHogEuHost;

    /// <summary>
    /// Gets the public PostHog project token used for event ingestion.
    /// </summary>
    public string ProjectToken { get; init; } = TelemetryDefaults.ProjectToken;

    /// <summary>
    /// Gets the source of the generated Connect or Deploy runtime payload.
    /// </summary>
    public string RuntimePayloadSource { get; init; } = TelemetryRuntimePayloadSources.Unknown;
}
