// Copyright (c) Foundry Project contributors.
// Licensed under the MIT License.
// See the LICENSE file in the project root for more information.

namespace Foundry.Core.Services.Configuration;

/// <summary>
/// Defines the shared length constraints for generated computer names.
/// </summary>
public static class MachineNamingRules
{
    /// <summary>
    /// Gets the number of characters generated for an automatic suffix.
    /// </summary>
    public const int AutoGeneratedSuffixLength = 6;

    /// <summary>
    /// Gets the maximum prefix length that preserves the generated suffix budget.
    /// </summary>
    public const int MaxPrefixLength = ComputerNameRules.MaxLength - AutoGeneratedSuffixLength;

    /// <summary>
    /// Normalizes and truncates a prefix to the supported generated-name budget.
    /// </summary>
    /// <param name="value">Configured computer-name prefix.</param>
    /// <returns>The normalized prefix.</returns>
    public static string NormalizePrefix(string? value)
    {
        string normalized = ComputerNameRules.Normalize(value);
        return normalized.Length > MaxPrefixLength
            ? normalized[..MaxPrefixLength]
            : normalized;
    }

    /// <summary>
    /// Determines whether a computer name contains a non-empty suffix after the configured prefix.
    /// </summary>
    /// <param name="computerName">Computer name to inspect.</param>
    /// <param name="prefix">Required computer-name prefix.</param>
    /// <returns><see langword="true" /> when the prefix matches and a suffix remains.</returns>
    public static bool HasSuffix(string? computerName, string? prefix)
    {
        string normalizedComputerName = ComputerNameRules.Normalize(computerName);
        string normalizedPrefix = NormalizePrefix(prefix);
        return normalizedComputerName.Length > normalizedPrefix.Length &&
               normalizedComputerName.StartsWith(normalizedPrefix, StringComparison.OrdinalIgnoreCase);
    }
}
