param(
    [ValidateSet('win-x64', 'win-arm64')]
    [string]$RuntimeIdentifier = 'win-x64',

    [Parameter(Mandatory = $true)]
    [ValidatePattern('^\d{2}\.\d{1,2}\.\d{1,2}-build\.\d+$')]
    [string]$PackVersion,

    [ValidateSet('Release', 'Debug')]
    [string]$Configuration = 'Release',

    [string]$VpkVersion = '0.0.1589-ga2c5a97'
)

$ErrorActionPreference = 'Stop'

$repoRoot = Split-Path -Parent $PSScriptRoot
$projectPath = Join-Path $repoRoot 'src\Foundry\Foundry.csproj'
$artifactsRoot = Join-Path $repoRoot 'artifacts\velopack'
$publishDir = Join-Path $artifactsRoot "publish\Foundry\$RuntimeIdentifier"
$releaseDir = Join-Path $artifactsRoot "releases\$RuntimeIdentifier"
$releaseAssetsDir = Join-Path $artifactsRoot 'release-assets'
$toolDir = Join-Path $repoRoot 'artifacts\tools\vpk'
$releaseNotesPath = Join-Path $artifactsRoot 'release-notes.md'
$platform = if ($RuntimeIdentifier -eq 'win-x64') { 'x64' } else { 'ARM64' }
$artifactArchitecture = if ($RuntimeIdentifier -eq 'win-x64') { 'x64' } else { 'arm64' }
$velopackChannel = $RuntimeIdentifier
$targetFramework = 'net10.0-windows10.0.26100.0'
$runtimeBuildDir = Join-Path $repoRoot "src\Foundry\bin\$platform\$Configuration\$targetFramework\$RuntimeIdentifier"

if (-not ($PackVersion -match '^(?<year>\d{2})\.(?<month>\d{1,2})\.(?<day>\d{1,2})-build\.(?<build>\d+)$')) {
    throw "PackVersion '$PackVersion' must use YY.M.D-build.Build."
}

$applicationVersion = '{0}.{1}.{2}.{3}' -f $Matches['year'], $Matches['month'], $Matches['day'], $Matches['build']

foreach ($path in @($publishDir, $releaseDir)) {
    if (Test-Path -Path $path) {
        Remove-Item -Path $path -Recurse -Force
    }

    New-Item -Path $path -ItemType Directory -Force | Out-Null
}

New-Item -Path $toolDir -ItemType Directory -Force | Out-Null
New-Item -Path $releaseAssetsDir -ItemType Directory -Force | Out-Null
New-Item -Path $artifactsRoot -ItemType Directory -Force | Out-Null

Get-ChildItem -Path $releaseAssetsDir -File -ErrorAction SilentlyContinue |
    Where-Object {
        $_.Name -eq "FoundrySetup-$artifactArchitecture.msi" -or
        $_.Name -eq "RELEASES-$velopackChannel" -or
        $_.Name -eq 'RELEASES' -or
        $_.Name -eq "assets.$velopackChannel.json" -or
        $_.Name -eq "releases.$velopackChannel.json" -or
        $_.Name -like "Foundry-*-$velopackChannel-full.nupkg" -or
        $_.Name -match '^Foundry-\d+(\.\d+){2}-build\.\d+-full\.nupkg$'
    } |
    Remove-Item -Force

$vpkExe = Join-Path $toolDir 'vpk.exe'
if (Test-Path -Path $vpkExe -PathType Leaf) {
    dotnet tool update vpk --tool-path $toolDir --version $VpkVersion
}
else {
    dotnet tool install vpk --tool-path $toolDir --version $VpkVersion
}

if ($LASTEXITCODE -ne 0) {
    throw "Unable to install or update vpk $VpkVersion."
}

Set-Content -Path $releaseNotesPath -Value "# Foundry $PackVersion`n`nRelease notes are generated by GitHub Releases during the release workflow." -NoNewline

dotnet publish $projectPath `
    -c $Configuration `
    -r $RuntimeIdentifier `
    --self-contained true `
    -o $publishDir `
    --nologo `
    -p:Platform=$platform `
    -p:PublishProfile= `
    -p:PublishTrimmed=false `
    -p:Version=$applicationVersion `
    -p:AssemblyVersion=$applicationVersion `
    -p:FileVersion=$applicationVersion `
    -p:InformationalVersion=$applicationVersion

if ($LASTEXITCODE -ne 0) {
    throw "dotnet publish failed for Foundry ($RuntimeIdentifier)."
}

$foundryExe = Join-Path $publishDir 'Foundry.exe'
if (-not (Test-Path -Path $foundryExe -PathType Leaf)) {
    throw "Expected Foundry executable was not published: '$foundryExe'."
}

$winUiResourceFiles = @('App.xbf', 'Foundry.pri')
foreach ($file in $winUiResourceFiles) {
    $source = Join-Path $runtimeBuildDir $file
    if (-not (Test-Path -Path $source -PathType Leaf)) {
        throw "Expected WinUI resource file was not built: '$source'."
    }

    Copy-Item -Path $source -Destination (Join-Path $publishDir $file) -Force
}

$winUiResourceDirectories = @('Themes', 'Views')
foreach ($directory in $winUiResourceDirectories) {
    $source = Join-Path $runtimeBuildDir $directory
    if (-not (Test-Path -Path $source -PathType Container)) {
        throw "Expected WinUI resource directory was not built: '$source'."
    }

    Copy-Item -Path $source -Destination $publishDir -Recurse -Force
}

& $vpkExe pack `
    --msi `
    --instLocation PerMachine `
    --packId Foundry `
    --packTitle Foundry `
    --packAuthors 'Foundry Contributors' `
    --packVersion $PackVersion `
    --packDir $publishDir `
    --mainExe Foundry.exe `
    --channel $velopackChannel `
    --runtime $RuntimeIdentifier `
    --outputDir $releaseDir `
    --icon (Join-Path $repoRoot 'src\Foundry\Assets\AppIcon.ico') `
    --releaseNotes $releaseNotesPath `
    --noPortable

if ($LASTEXITCODE -ne 0) {
    throw "vpk pack failed for Foundry ($RuntimeIdentifier)."
}

$msi = Get-ChildItem -Path $releaseDir -Filter '*.msi' -File | Select-Object -First 1
if ($null -eq $msi) {
    throw "Velopack did not create an MSI in '$releaseDir'."
}

$msiArtifact = Join-Path $releaseAssetsDir "FoundrySetup-$artifactArchitecture.msi"
Copy-Item -Path $msi.FullName -Destination $msiArtifact -Force

Get-ChildItem -Path $releaseDir -File |
    Where-Object {
        $_.Name -like 'RELEASES*' -or
        $_.Name -like 'assets.*.json' -or
        $_.Name -like 'releases.*.json' -or
        $_.Extension -eq '.nupkg'
    } |
    Copy-Item -Destination $releaseAssetsDir -Force

Write-Host "Published Foundry Velopack MSI: $msiArtifact"
Write-Host "Velopack release metadata: $releaseDir"
